main_window_config:
  name: "Tamarindo Engine"
  width: 400
  height: 400
vertex_data: [
# pos (x, y, z) tex_coord (u, v)
    0.0, 1.0, 0.0, 1.0, 0.0, # top right
    0.0, 0.0, 0.0, 0.0, 0.0, # top left
    1.0, 0.0, 0.0, 0.0, 1.0, # bottom left
    1.0, 1.0, 0.0, 1.0, 1.0, # bottom right
  ]
index_data: [0, 1, 2, 2, 3, 0]
